[package]
name = "rusty-moon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
jsonrpsee = { version = "0.24.0", features = ["tokio", "ws-client"] }
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
